select * from dim_customer;
select count(*) from dim_customer;
select count(distinct customer_code) from dim_customer;
select count(distinct customer) from dim_customer;
select count(distinct platform) from dim_customer;
select count(distinct channel) from dim_customer;
select count(distinct market) from dim_customer;
select count(distinct region) from dim_customer;
select distinct region from dim_customer;
select distinct channel from dim_customer;